name: Continuous Integration
on: [push, pull_request]

jobs:

  build-documentation:
    name: Build documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up build environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r dev_requirements.txt
      - name: Build documentation
        run: |
          source venv/bin/activate
          cd documentation/user_doc
          mkdocs build --clean --site-dir ../../results/documentation/
      - uses: actions/upload-artifact@v4
        with:
            name: Documentation
            path: results/documentation/*
            if-no-files-found: error


  package:
    name: Package python wheel
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.8"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Build package
        run: uv build
      - name: Run unit tests
        # TODO should be able to run all tests from top directory!!!
        run: |
          cd test/unit
          uv run python -m unittest --verbose
      - name: Run component tests
        # TODO should be able to run all tests from top directory!!! and not necessitate any directory creation
        run: |
          cd test/component
          mkdir results
          mkdir tmp
          uv run python -m unittest --verbose
      - uses: actions/upload-artifact@v4
        with:
            name: Wheel package
            path: dist
            if-no-files-found: error

