name: Continuous Integration
on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.8"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Build package
        run: uv build
      - name: Build documentation
        run: uv --directory documentation/user_doc run mkdocs build --clean --site-dir ../../results/documentation/
      - name: Run unit tests
        # TODO should be able to run all tests from top directory!!!
        run: |
          cd test/unit
          uv run python -m unittest --verbose
      - name: Run component tests
        # TODO should be able to run all tests from top directory!!! and not necessitate any directory creation
        run: |
          cd test/component
          mkdir results
          mkdir tmp
          uv run python -m unittest --verbose
      - uses: actions/upload-artifact@v4
        with:
            name: Wheel package
            path: dist
            if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
            name: Documentation
            path: results/documentation/*
            if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            documentation/*
            dist/*