name: Continuous Integration
on: [push, pull_request]

jobs:

  tests-unit:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up test environment
        working-directory: test/unit
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r ../../requirements.txt
      - name: Run tests
        working-directory: test/unit
        run: |
          source venv/bin/activate
          PYTHONUNBUFFERED=true PYTHONPATH=../../source python -m unittest --verbose
